# Generated by Django 4.1.4 on 2022-12-17 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="bankdata",
            fields=[
                ("name_primary_key", models.CharField(max_length=30)),
                ("pin", models.CharField(max_length=30)),
                (
                    "bank_account_num",
                    models.IntegerField(primary_key=True, serialize=False, unique=True),
                ),
                ("contact_num", models.IntegerField()),
                ("email", models.EmailField(max_length=50, unique=True)),
            ],
        ),
    ]
